name: "Learn To Code Using Swift"
description: ""
language: "en-US"
navigation:
    - label: "Summary"
      url: "/"
    - label: "Authors"
      url: "/#authors"
    - label: "Chapters"
      url: "/#chapters"
    - label: "FAQ"
      url: "/#faq"
    - label: "Contact"
      url: "/#contact"

footer:
    